<a href="https://colab.research.google.com/github/priyanshhu2211/DSV-Lab/blob/main/Pandas_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
student_data = {
    'Name': ['Aarav', 'Diya', 'Kabir', 'Meera'],
    'Age': [20, 19, 21, 20],
    'City': ['Delhi', 'Mumbai', 'Pune', 'Jaipur']
}
student_df = pd.DataFrame(student_data)
student_df

    Name  Age    City
0  Aarav   20   Delhi
1   Diya   19  Mumbai
2  Kabir   21    Pune
3  Meera   20  Jaipur

In [3]:
display(student_df)

    Name  Age    City
0  Aarav   20   Delhi
1   Diya   19  Mumbai
2  Kabir   21    Pune
3  Meera   20  Jaipur

In [4]:
print(student_df.columns)

Index(['Name', 'Age', 'City'], dtype='object')

In [5]:
student_df['Name']

0    Aarav
1     Diya
2    Kabir
3    Meera
Name: Name, dtype: object

In [6]:
student_df['City']

0     Delhi
1    Mumbai
2      Pune
3    Jaipur
Name: City, dtype: object

In [7]:
student_city_df = student_df[['Name', 'City']]
student_city_df

    Name    City
0  Aarav   Delhi
1   Diya  Mumbai
2  Kabir    Pune
3  Meera  Jaipur

In [8]:
book_data = {
    'Book': ['Wings of Fire', 'The Alchemist', '1984'],
    'Author': ['A. P. J. Abdul Kalam', 'Paulo Coelho', 'George Orwell'],
    'Price': [250, 300, 220]
}
book_df = pd.DataFrame(book_data)
book_df

            Book                Author  Price
0  Wings of Fire  A. P. J. Abdul Kalam    250
1  The Alchemist          Paulo Coelho    300
2           1984         George Orwell    220

In [9]:
book_df['Publisher'] = 'ABC Publications'
book_df

            Book                Author  Price         Publisher
0  Wings of Fire  A. P. J. Abdul Kalam    250  ABC Publications
1  The Alchemist          Paulo Coelho    300  ABC Publications
2           1984         George Orwell    220  ABC Publications

In [10]:
serial_df = pd.DataFrame({'Student': ['A', 'B', 'C', 'D', 'E']})
serial_df['SerialNo'] = np.arange(5)
serial_df

  Student  SerialNo
0       A         0
1       B         1
2       C         2
3       D         3
4       E         4

In [11]:
del serial_df['SerialNo']
serial_df

  Student
0       A
1       B
2       C
3       D
4       E

In [12]:
movie_df = pd.DataFrame({
    'Movie': ['3 Idiots', 'Dangal', 'Chhichhore'],
    'Year': [2009, 2016, 2019],
    'Rating': [8.4, 8.3, 8.3]
})
movie_df

        Movie  Year  Rating
0    3 Idiots  2009     8.4
1      Dangal  2016     8.3
2  Chhichhore  2019     8.3

In [13]:
movie_selected_df = movie_df.reindex(columns=['Movie', 'Rating', 'Director'])
movie_selected_df

        Movie  Rating  Director
0    3 Idiots     8.4       NaN
1      Dangal     8.3       NaN
2  Chhichhore     8.3       NaN

In [14]:
city_series = pd.Series(['Delhi', 'Mumbai'], index=[0, 3])
city_series

0     Delhi
3    Mumbai
dtype: object

In [15]:
branch_df = pd.DataFrame({'Student': ['A', 'B', 'C', 'D']})
branch_df['Branch'] = city_series
branch_df

  Student  Branch
0       A   Delhi
1       B     NaN
2       C     NaN
3       D  Mumbai

In [16]:
employee_df = pd.DataFrame({
    'Employee': ['Aman', 'Bhavna', 'Charu', 'Dev', 'Esha'],
    'Department': ['IT', 'HR', 'Sales', 'IT', 'Finance'],
    'Experience': [2, 5, 3, 4, 1]
})
employee_exp_df = employee_df[['Employee', 'Experience']]
employee_exp_df

  Employee  Experience
0     Aman           2
1   Bhavna           5
2    Charu           3
3      Dev           4
4     Esha           1

In [17]:
display(employee_df['Department'])
print(employee_df.columns)

0         IT
1         HR
2      Sales
3         IT
4    Finance
Name: Department, dtype: object

Index(['Employee', 'Department', 'Experience'], dtype='object')

In [18]:
employee_df['Office'] = 'Head Office'
employee_df

  Employee Department  Experience       Office
0     Aman         IT           2  Head Office
1   Bhavna         HR           5  Head Office
2    Charu      Sales           3  Head Office
3      Dev         IT           4  Head Office
4     Esha    Finance           1  Head Office

In [19]:
employee_df['Office'] = np.arange(5)
employee_df

  Employee Department  Experience  Office
0     Aman         IT           2       0
1   Bhavna         HR           5       1
2    Charu      Sales           3       2
3      Dev         IT           4       3
4     Esha    Finance           1       4

In [20]:
office_names = pd.Series(['Delhi', 'Mumbai', 'Pune'], index=[0, 2, 4])
employee_df['Office'] = office_names
employee_df

  Employee Department  Experience  Office
0     Aman         IT           2   Delhi
1   Bhavna         HR           5     NaN
2    Charu      Sales           3  Mumbai
3      Dev         IT           4     NaN
4     Esha    Finance           1    Pune

In [21]:
del employee_df['Office']
employee_df

  Employee Department  Experience
0     Aman         IT           2
1   Bhavna         HR           5
2    Charu      Sales           3
3      Dev         IT           4
4     Esha    Finance           1

In [22]:
product_df = pd.DataFrame({
    'Product': ['Laptop', 'Phone', 'Tablet'],
    'Category': ['Electronics', 'Electronics', 'Electronics'],
    'Price': [55000, 25000, 18000]
})
product_ordered_df = product_df[['Price', 'Product', 'Category']]
product_ordered_df

   Price Product     Category
0  55000  Laptop  Electronics
1  25000   Phone  Electronics
2  18000  Tablet  Electronics

In [23]:
source_df = pd.DataFrame({
    'Name': ['Asha', 'Rohan', 'Ishita'],
    'Age': [19, 20, 18],
    'City': ['Agra', 'Noida', 'Mathura']
})
requested_df = source_df.reindex(columns=['Name', 'Age', 'City', 'Course'])
requested_df

     Name  Age     City  Course
0    Asha   19     Agra     NaN
1   Rohan   20    Noida     NaN
2  Ishita   18  Mathura     NaN

In [24]:
marks_df = pd.DataFrame({
    'Name': ['Aman', 'Diya', 'Kabir'],
    'Total Marks': [85, 92, 78]
})
marks_df['Total Marks']

0    85
1    92
2    78
Name: Total Marks, dtype: int64

In [25]:
course_df = pd.DataFrame({
    'Student': ['Aarav', 'Diya', 'Kabir', 'Meera', 'Rohan'],
    'Course': ['Python', 'Java', 'C', 'Python', 'Java'],
    'Score': [88, 91, 76, 95, 84]
})
print(course_df.columns)
display(course_df['Student'])
student_score_df = course_df[['Student', 'Score']]
display(student_score_df)
course_df['Batch'] = '2026'
course_df

Index(['Student', 'Course', 'Score'], dtype='object')

0    Aarav
1     Diya
2    Kabir
3    Meera
4    Rohan
Name: Student, dtype: object

  Student  Score
0   Aarav     88
1    Diya     91
2   Kabir     76
3   Meera     95
4   Rohan     84

  Student  Course  Score Batch
0   Aarav  Python     88  2026
1    Diya    Java     91  2026
2   Kabir       C     76  2026
3   Meera  Python     95  2026
4   Rohan    Java     84  2026

In [26]:
travel_df = pd.DataFrame({
    'Destination': ['Agra', 'Jaipur', 'Delhi', 'Lucknow', 'Varanasi']
})
travel_df['Code'] = np.arange(5)
display(travel_df)

travel_codes = pd.Series([101, 104], index=[1, 4])
travel_df['Code'] = travel_codes
display(travel_df)

  Destination  Code
0        Agra     0
1      Jaipur     1
2       Delhi     2
3     Lucknow     3
4    Varanasi     4

  Destination   Code
0        Agra    NaN
1      Jaipur  101.0
2       Delhi    NaN
3     Lucknow    NaN
4    Varanasi  104.0

In [27]:
school_df = pd.DataFrame({
    'Student': ['Anaya', 'Vihaan', 'Sara', 'Arjun'],
    'Class': [9, 10, 9, 10],
    'Section': ['A', 'B', 'A', 'C']
})
school_extended_df = school_df.reindex(columns=['Student', 'Class', 'Section', 'House'])
school_extended_df['House'] = 'Blue House'
school_extended_df

  Student  Class Section       House
0   Anaya      9       A  Blue House
1  Vihaan     10       B  Blue House
2    Sara      9       A  Blue House
3   Arjun     10       C  Blue House

In [28]:
inventory_df = pd.DataFrame({
    'Item': ['Pen', 'Notebook', 'Pencil', 'Eraser'],
    'Quantity': [50, 30, 40, 25]
})
stock_series = pd.Series([100, 200], index=[0, 2])
inventory_df['StockCode'] = stock_series
display(inventory_df)

del inventory_df['StockCode']
display(inventory_df)

       Item  Quantity  StockCode
0       Pen        50      100.0
1  Notebook        30        NaN
2    Pencil        40      200.0
3    Eraser        25        NaN

       Item  Quantity
0       Pen        50
1  Notebook        30
2    Pencil        40
3    Eraser        25